#!/bin/csh -f
# Installs ec
# Be sure to add ~/.local/bin into your path.
set supportedPythonVersions = (3.3)


foreach vers ($supportedPythonVersions)
    # remove build directories from a previous install to assure a clean install
    rm -rf build dist pw.egg-info
    echo ""
    which python$vers >& /dev/null
    if ($status == 0) then
	echo "### Installing to Python$vers."
	python$vers setup.py install --quiet --user

	# setuptools no longer installs man pages properly, so I must fix things up
	foreach sect (1 3 5)
	    mkdir -p ~/.local/man/man$sect
	    rm -f ~/.local/man/man$sect/pw.$sect
	    ln -s ~/.local/lib/python$vers/site-packages/pw-*.egg/man/man$sect/pw.$sect ~/.local/man/man$sect
	end
    else
	echo "### Cannot install to Python$vers, it is not available."
    endif
end

# remove build directories, because I like a clean directory
rm -rf build dist pw.egg-info

