#!/bin/csh -f
# Installs pw
#
# Requires 2.7 or Python3.3. Also requires the following packages
#     # yum install python
#     # yum install python-setuptools (for installation)
#     # yum install python-docutils (for manpages)
#     # yum install python-PyYAML (for archives)
#     # easy_install python-gnupg
#     # easy_install argparse
#     # yum install xdotool (autotype support)
#     # yum install xsel (clipboard support)
#     # yum install zenity (account selection when window title is not enough)  
#
# Alternatively, you can install Python from source. First get and install 
# Python using::
#     $ cd ~/packages/python
#     $ wget http://www.python.org/download/releases/3.3.2/Python-3.3.2.tgz
#     $ tar zxf Python-3.3.2.tgz
#     $ cd Python-3.3.2
#     $ ./configure --prefix=$HOME/.local
#     $ make
#     $ make install
#
# Now get easy_install::
#     $ wget -O http://python-distribute.org/distribute_setup.py
#     $ python3.3 distribute_setup.py
#
# Then you can use easy_install to install python-gnupg, argparse, docutils, and 
# PyYAML as above.

# Set python to the version of python you wish to use (ex. python2 or python3)
set python=python

# run pylint to find egregious errors
# this is optional, you can delete this line if you don't have pylint
pylint -E --disable=no-member charsets cursor dialog fileutils manpage pw secrets

# Determine the version of python we are using
set vers=`$python -c 'import sys; print("%s.%s" % (sys.version_info[0], sys.version_info[1]))'`
echo "Installing pw to ~/.home/bin (Python$vers)."

# remove build directories from a previous install to assure a clean install
rm -rf build dist pw.egg-info install.out

# install pw
python$vers setup.py install --quiet --user >& install.out
if ($status) then
    echo "Problems found, aborting (see install.out)"
    exit(1)
endif

# setuptools no longer installs man pages properly, so I must fix things up
foreach sect (1 3 5)
    mkdir -p ~/.local/man/man$sect
    rm -f ~/.local/man/man$sect/pw.$sect
    ln -s ~/.local/lib/python$vers/site-packages/pw-*.egg/man/man$sect/pw.$sect ~/.local/man/man$sect
end

# remove build directories, because I like a clean directory
rm -rf build dist pw.egg-info
