#!/usr/bin/env bash
# Installs abraxas
#
# Requires 2.7 or Python3.3. Also requires the following packages
#     # yum install python
#     # yum install python-setuptools (for installation)
#     # yum install python-docutils (for manpages)
#     # yum install python-PyYAML (for archives)
#     # easy_install python-gnupg
#     # easy_install argparse
#     # yum install xdotool (autotype support)
#     # yum install xsel (clipboard support)
#
# Alternatively, you can install Python from source. First get and install 
# Python using::
#     $ cd ~/packages/python
#     $ wget http://www.python.org/download/releases/3.3.2/Python-3.3.2.tgz
#     $ tar zxf Python-3.3.2.tgz
#     $ cd Python-3.3.2
#     $ ./configure --prefix=$HOME/.local
#     $ make
#     $ make install
#
# Now get easy_install::
#     $ wget -O http://python-distribute.org/distribute_setup.py
#     $ python3.3 distribute_setup.py
#
# Then you can use easy_install to install python-gnupg, argparse, docutils, and 
# PyYAML as above.

# Set python to the version of python you wish to use (ex. python2 or python3).
python=python

# Run pylint to find egregious errors.
# This is optional, you can delete this line if you don't have pylint.
#pylint -E --disable=no-member abraxas manpage

# Determine the version of python we are using.
vers=$($python -c 'import sys; print("%s.%s" % (sys.version_info[0], sys.version_info[1]))')
echo "Installing abraxas to ~/.local/bin (Python$vers)."

# Remove build directories from a previous install to assure a clean install.
rm -rf build dist abraxas.egg-info install.out

# Install abraxas
python$vers setup.py install --quiet --user >& install.out
if [ $? -ne 0 ] ; then
    echo "Problems found, aborting (see install.out)"
    exit 1
fi

# Setuptools no longer installs man pages properly, so I must fix things up.
for sect in 1 3 5
do
    mkdir -p ~/.local/man/man$sect
    rm -f ~/.local/man/man$sect/abraxas.$sect
    ln -s ~/.local/lib/python$vers/site-packages/abraxas-*.egg/man/man$sect/abraxas.$sect ~/.local/man/man$sect
        # if you get 'failed to create symbolic link' messages here, it is 
        # because you still have a previous version installed. You must manually 
        # delete them before installing.
done

# Rename the executable to abraxas.
mv ~/.local/bin/main.py ~/.local/bin/abraxas

# Remove build directories, because I like a clean directory.
rm -rf build dist abraxas.egg-info
